version: 2.1
orbs:
    node: circleci/node@5.0.0
    # vercel-orb: i-am-jeetu/vercel-orb@1.0.0
    # aws-cli: circleci/aws-cli@2.0.6
    # eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
    BuildAndDeploy:
        docker:
            - image: cimg/base:stable
        steps:
            - node/install
            - checkout
            - run:
                  name: Installing Deta CLI
                  command: |
                      curl -fsSL https://get.deta.dev/cli.sh | sh
            - run:
                  name: Installing Modules
                  command: |
                      npm i
            - run:
                  name: Testing
                  command: |
                      npm run test:prod
            - run:
                  name: Cleaning
                  command: |
                      npm run clean
            - run:
                  name: Building
                  command: |
                      npm run build
            - run:
                  name: Deployment
                  command: |
                      npm run deploy
    # deploy:
    # executor: vercel/default
    # steps:
    #     - checkout
    #     - vercel/install
    #     - vercel/check-authentication
    #     - run:
    #           command: >
    #               echo "The command above installs Vercel, the command below deploys.
    #               What you do inbetween is up to you!"
    #     - vercel/deploy
workflows:
    build-deploy:
        jobs:
            - BuildAndDeploy:
                  filters:
                      branches:
                          only:
                              - appDeployment
            # - deploy
