version: 2.1
orbs:
    node: circleci/node@5.0.0
    heroku: circleci/heroku@1.2.6
jobs:
    build:
        docker:
            - image: cimg/base:stable
        steps:
            - node/install
            - checkout
            - run:
                  name: Cleaning
                  command: |
                      npm run clean:bash
            - run:
                  name: Building
                  command: |
                      npm run build:bash

    test:
        docker:
            - image: cimg/base:stable
        steps:
            - node/install
            - checkout
            - run:
                  name: Installing Modules
                  command: |
                      npm i
            - run:
                  name: Testing
                  command: |
                      npm run test:prod

    deploy:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - run:
                  name: Deploy Branch to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
workflows:
    build-test-deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - main
            - test:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
            - deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only: main
